---
title: "The role of brain structure in the association between pubertal timing and depression risk in an early adolescent sample (the ABCD Study®): A registered report"
author: Niamh MacSweeney, niamh.macsweeney@ed.ac.uk, Division of Psychiatry, Centre for Clinical Brain Sciences, University of Edinburgh
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### Introduction

This is a README file for the project: The role of brain structure in the association between pubertal timing and depression risk in an early adolescent sample (the ABCD Study®): A registered report by MacSweeney et al.

If you have any questions about this project or repository, please contact Niamh MacSweeney (niamh.macsweeney@ed.ac.uk)

This project is current under review as a Stage One Registered Report. As soon as an in principle acceptance is issued, the Stage One manuscript will be uploaded to a public server (e.g., OSF) and the link will be provided here. 

#### Set Up

Please see the Division of Pychiatry ABCD User Guide for information on local access to ABCD data and general guidelines on using this dataset. 

ABCD User Guide: https://niamhmacsweeney.github.io/ABCD_data_management/


#### Folder Set Up
There are three main folders:

  1. PREP: Scripts for data cleaning and manipulation
  2. ANALY: Scripts for pilot analysis
  3. FUNCTIONS: Functions for use in analysis scripts

File naming system: TYPE_variable_datarelease.filetype  e.g., PREP_pds_R4.0.csv = prep file for pubertal development scale.csv from data release 4.0.
