---
title: "PREP_CBCL_R3.0"
author: "Niamh MacSweeney"
date: "30/11/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

The purpose of this script is to generate a summary depression ratings from the CBCL. This script is adapted from "PREP.Questionnaires.R" by X.Shen 

#### SETUP
Load libraries needed and set working directory
```{r, load libraries, data, set wd}

library(dplyr)

setwd("/Volumes/GenScotDepression/users/niamh/puberty_ABCD/ABCD_puberty_depression/prep")


cbcl <-rio::import("/Volumes/GenScotDepression/users/niamh/ABCD_release3.0/iii.data/Mental_Health/abcd_cbcls01.rds")

head(pds, n=10) #first few observations
str(pds)  #types of variables
names(pds) #List variables in dataframe

#reduce to baseline data only, N=11,878
pds <- pds %>% 
  filter(eventname == "baseline_year_1_arm_1")
```

```{r, function set up}

dir.var.ls='/Volumes/GenScotDepression/users/niamh/puberty_ABCD/ABCD_puberty_depression/functions/data_tables_for_functions/ls.questionnaires.csv'
ls.var=read.csv(dir.var.ls,stringsAsFactors=FALSE,sep = '\t',quote = '')
ls.files.tocatch=paste0(ls.var$Category,'/',ls.var$File.name)
ls.files.tocatch=unique(ls.files.tocatch)
for (i in ls.files.tocatch){
      tmp.file=readRDS(paste0(tab.dat.dir,'/',i,'.rds'))
      ## follow-up track file have duplicated IDs. Only keep the baseline data. 
      if (length(unique(tmp.file$src_subject_id))<length(tmp.file$src_subject_id)){
            tmp.file = tmp.file[order(tmp.file$interview_date),]
            tmp.file = tmp.file[!duplicated(tmp.file$src_subject_id),]}
      
      if (i==ls.files.tocatch[1]){questn.dat=tmp.file}else{
                  cols.keep=!grepl('interview_date|interview_age|sex|gender|eventname',colnames(tmp.file))
                  tmp.file=tmp.file[,cols.keep]
                  questn.dat=merge(questn.dat,tmp.file,by='src_subject_id',all=T)                  
            }
}


# grep('\\.x$',colnames(IM.dat))  # check if there is any duplicated colnames
rm(i,tmp.file)

questn.dat=questn.dat[,ls.var$Field.name]

######################################################  preproc data ######################################################################

targetdat=questn.dat
targetdat.clean=targetdat

```

