---
title: "Brain Plots"
author: "Niamh MacSweeney"
date: "10/25/2021"
output: html_document
---
The purpose of this script is to create visualisation aids of the ROIs identified in the pilot analysis for the puberty-depression ABCD RR. 

See this tutorial for information: https://journals.sagepub.com/doi/full/10.1177/2515245920928009

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### Set Up

```{r, load packages and data}

#load packages
library(ggseg)
library(ggplot2)
library(dplyr)

#set wd
setwd("/Volumes/GenScotDepression/users/niamh/puberty_ABCD/ABCD_puberty_depression/results")

#load ROI data files

f_dep_brain <-rio::import("/Volumes/GenScotDepression/users/niamh/puberty_ABCD/ABCD_puberty_depression/results/ROIs_dep_brain_females_pilot_analysis_withCI.RData")

m_dep_brain <- rio::import("/Volumes/GenScotDepression/users/niamh/puberty_ABCD/ABCD_puberty_depression/results/ROIs_dep_brain_males_pilot_analysis_withCI.RData")

f_pt_brain <- rio::import("/Volumes/GenScotDepression/users/niamh/puberty_ABCD/ABCD_puberty_depression/results/ROIs_PT_females_brain_pilot_analysis_withCI.RData")

m_pt_brain <- rio::import("/Volumes/GenScotDepression/users/niamh/puberty_ABCD/ABCD_puberty_depression/results/ROIs_PT_males_brain_pilot_analysis_withCI.RData")

```

```{r, try plotting ROIs female dep~brain}

f_dep_brain_tmp <- tibble(
  region = rep(c("accumbens area", "transverse temporal"), 2), 
  p = sample(seq(0,.5,.001), 8),
  groups = c(rep("g1", 4), rep("g2", 4))
)


```


